# NumPy 
(**Num**erical **Py**thon)

* used for working with arrays.
* In Python we have lists that serve the purpose of arrays, but they are slow to process.
* NumPy is incredible library to perform mathematical and statistical operations due to it's fast and memory efficient as it is optimized to work with latest CPU architectures.
* NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.So processes can access and manipulate them very efficiently.

In [1]:
import numpy as np

**0-D**

In [ ]:
a=45
print(a)
print(type(a))

In [ ]:
a="srk"
arr_0 = np.array(a)
print(arr_0)
print(type(arr_0))

In [ ]:
#ndim - no.of dimensions

arr_0.ndim           

In [ ]:
arr_0.shape

**1-D**

In [ ]:
t = [1,20,5,20,5,1,1,1,4.5,True,"srk"]

a = np.array(t)  #np.array((1,20,4.5,False,20))
print(a)

In [ ]:
a.ndim

In [ ]:
a.shape

In [ ]:
l=[20,4,55]

a= np.array(l)
print(a)

In [ ]:
a.ndim

In [ ]:
a.shape

**convert a list to array**

In [ ]:
l=[15,19,24]

a= np.array(l)
print(a)

In [ ]:
#1D array to list
a= np.array([5,25,50])
a.tolist()

**Functions for creating 1D array**

- 1D array with own values (list -- array)

In [2]:
#list to 1D array
l=[14,11,19,24]
a=np.array(l)
print(a)

[14 11 19 24]


- 1D array with sequence

In [3]:
a = np.arange(10,20)
print(a)

[10 11 12 13 14 15 16 17 18 19]


- 1D array with random values

In [4]:
a= np.random.randint(1,100,7)
print(a)

[30 37 22 90 90 26 35]


- 1D array with same value

In [5]:
a = np.zeros(4,dtype=int)+11
print(a)

[11 11 11 11]


# Extract or Select

**Accessing elements/ Extracting the values**

1. Accessing a single value through Indexing
2. Accessing a multiple values based on slicing (when there is pattern)
3. Accessing a multiple values based on indexing (when there is no pattern)
4. Accessing a single or multiple values based on condition

In [6]:
a = np.array([15,19,24,32,37,42,46])
print(a)

[15 19 24 32 37 42 46]


**1. Accessing a single value through Indexing**

In [7]:
#positive indexing
print(a[3])

32


In [8]:
print(a[-4])

32


**2. Accessing a multiple values based on slicing**

In [9]:
a[0:7:2]

array([15, 24, 37, 46])

In [10]:
a[1:4]

array([19, 24, 32])

In [11]:
a[1:4:-1]

array([], dtype=int64)

**3. Accessing a multiple values based on indexing**

Syntax : array[list of index numbers]

In [12]:
a[[0,1,4,5]]

array([15, 19, 37, 42])

In [13]:
a[[0,1,2,0,2,0,3]]

array([15, 19, 24, 15, 24, 15, 32])

**4. Accessing a multiple values based on condition (Mask Indexing or Fancy Indexing)**

Syntax: array[condition]

-- first, it will check the condition, the item which satisifies the condition (means which item gives True for the condition), that item will be selected

In [14]:
a[a>30]

array([32, 37, 42, 46])

In [15]:
#inside a, select data where condition is True 
a[a%2==0]

array([24, 32, 42, 46])

In [18]:
a[(a<30) | (a>40)]

array([15, 19, 24, 42, 46])

# Data Manipulation or Data Modification in 1D Array

- Insert or Add
- Delete or Remove
- Update or Replace

In [19]:
a = np.array([15,19,24])
print(a)

[15 19 24]


**Add a value in a array**4

syntax to add a single value : np.append(array,singlevalue)

syntax to add a multiple values : np.append(array,list of values)

In [20]:
a1 = np.append(a,50)
print(a1)

[15 19 24 50]


In [21]:
a2 = np.append(a,[60,70,80])
print(a2)

[15 19 24 60 70 80]


**Replacing a single index position with single value in a 1D array**

In [ ]:
a  = np.array([15,19,24,37,42,26])
print(a)

In [ ]:
a[1] = 27
print(a)

**Replacing a multiple index positions with a single value in a array**

In [ ]:
a[[0,1,4,5]] = 10
print(a)

**Replacing a multiple index positions with a multiple values in a array**

In [ ]:
a[[0,1,4]] = [20,19,45]
print(a)

**Delete a single value in a array**

Syntax: np.delete(array,indexnumber) 

In [22]:
a  = np.array([15,19,24,37,42,26])
print(a)

[15 19 24 37 42 26]


In [23]:
a3 = np.delete(a,1)
print(a3)

[15 24 37 42 26]


**Delete a multiple values in a array**

Syntax : np.delete(array,[multiple index numbers]]

In [24]:
a4  = np.delete(a,[1,3,4])         # deleting multiple values
print(a4)

[15 24 26]


**Sorting an Array**

In [2]:
a = np.array([4,6,8,2,1])

b = np.sort(a)
print(b)

[1 2 4 6 8]


**shallow copy**

In [3]:
a= np.array([1,2,3])
b= a.copy()

b[1]=20
print(a)
print(b)

[1 2 3]
[ 1 20  3]


# Operations using 1D array

**Arthimetic Oprations**

In [4]:
a = np.array([10, 20, 30])
print(a)

[10 20 30]


In [12]:
a.shape

(3,)

In [5]:
b = a+1
print(b)

[11 21 31]


In [6]:
c = a+0
print(c)

[10 20 30]


In [7]:
d = a**2
print(d)

[100 400 900]


In [13]:
print(a+b)

[21 41 61]


In [14]:
print(a-b)

[-1 -1 -1]


In [15]:
print(a*b)

[110 420 930]


**Comparision operations**

In [16]:
c <= 10

array([ True, False, False])

In [18]:
c >= a

array([ True,  True,  True])

In [19]:
a == c

array([ True,  True,  True])

In [20]:
np.array_equal(a,c)

True

**Mathematical operations**

In [21]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [22]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [23]:
np.log(a)

array([0.        , 0.69314718, 1.09861229])

In [24]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081])